//
// Created by Alex Powers on 21-02-2019.
//
// https://itk.org/Doxygen/html/classitk_1_1ThresholdImageFilter.html

#include "SimpleThresholdCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()

// ITK Imports
#include "itkImage.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"
#include "itkBinaryThresholdImageFilter.h"


int main(int argc, char *argv[]) {
    PARSE_ARGS;  // <--- This is always the first line and is defined in SimpleThresholdCLP.h

    std::cout << "The input volume is: " << inputVolume << std::endl;
    std::cout << "The output volume is: " << outputVolume << std::endl;
    std::cout << "The lowThreshold value is: " << lowThreshold << std::endl;
    std::cout << "The highThreshold value is: " << highThreshold << std::endl;
    std::cout << "The inside value is: " << insideValue << std::endl;
    std::cout << "The outside value is: " << outsideValue << std::endl;

    // define dimension
    constexpr unsigned int dimension = 3;

    // define input image type
    using InputPixelType = unsigned char;
    using InputImageType = itk::Image<InputPixelType, dimension>;

    // define output image type
    using OutputPixelType =  unsigned char;
    using OutputImageType = itk::Image<OutputPixelType, dimension>;

    // define reader
    using ReaderType = itk::ImageFileReader<InputImageType>;
    typename ReaderType::Pointer reader = ReaderType::New();
    // set reader filename
    reader->SetFileName(inputVolume);


    // define filter
    using FilterType = itk::BinaryThresholdImageFilter<InputImageType, OutputImageType>;
    typename FilterType::Pointer filter = FilterType::New();

    // define filter parameters
    filter->SetLowerThreshold(lowThreshold);
    filter->SetUpperThreshold(highThreshold);
    filter->SetOutsideValue(outsideValue);
    filter->SetInsideValue(insideValue);
    filter->SetInput(reader->GetOutput());

    // define writer
    using WriterType = itk::ImageFileWriter<OutputImageType>;
    typename WriterType::Pointer writer = WriterType::New();

    // set writer output name
    writer->SetFileName(outputVolume);
    // link filter output to writer input
    writer->SetInput(filter->GetOutput());

    try {
        writer->Update();
    }
    catch (itk::ExceptionObject &err) {
        std::cerr << "EXCEPTION! OH MY!" << std::endl;
        std::cerr << err << std::endl;
        return EXIT_FAILURE;
    }
    return EXIT_SUCCESS;
}