//
// Created by Alex Powers on 21-02-2019.
//

#include "GaussianLPFCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()

// ITK Imports
#include "itkImage.h"
#include "itkImageFileWriter.h"
#include "itkImageFileReader.h"
#include "itkRecursiveGaussianImageFilter.h"

int main(int argc, char *argv[]) {
    PARSE_ARGS;

    std::cout << "The input volume is: " << inputVolume << std::endl;
    std::cout << "The output volume is: " << outputVolume << std::endl;
    std::cout << "The sigma value is: " << sigma << std::endl;


    // define dimension
    constexpr unsigned int dimension = 3;

    // define input image type
    using InputPixelType = unsigned char;
    using InputImageType = itk::Image<InputPixelType, dimension>;

    // define output image type
    using OutputPixelType =  unsigned char;
    using OutputImageType = itk::Image<OutputPixelType, dimension>;

    // define reader
    using ReaderType = itk::ImageFileReader<InputImageType>;
    typename ReaderType::Pointer reader = ReaderType::New();
    // set reader filename
    reader->SetFileName(inputVolume);

    // define filter
    using FilterType = itk::RecursiveGaussianImageFilter<InputImageType, OutputImageType>;
    typename FilterType::Pointer filter = FilterType::New();
    // define filter parameters
    filter->SetSigma(sigma);
    filter->SetInput(reader->GetOutput());

    // define writer
    using WriterType = itk::ImageFileWriter<OutputImageType>;
    typename WriterType::Pointer writer = WriterType::New();

    // set writer output name
    writer->SetFileName(outputVolume);
    // link filter output to writer input
    writer->SetInput(filter->GetOutput());

    try {
        writer->Update();
    }
    catch (itk::ExceptionObject &err) {
        std::cerr << "EXCEPTION! OH MY!" << std::endl;
        std::cerr << err << std::endl;
        return EXIT_FAILURE;
    }
    return EXIT_SUCCESS;


}